-- CreateTable
CREATE TABLE "Block" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "favAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "blockId" TEXT NOT NULL,
    "blockedById" TEXT NOT NULL,
    CONSTRAINT "Block_blockId_fkey" FOREIGN KEY ("blockId") REFERENCES "Profile" ("userId") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "Block_blockedById_fkey" FOREIGN KEY ("blockedById") REFERENCES "Profile" ("userId") ON DELETE RESTRICT ON UPDATE CASCADE
);
