# fly.toml app configuration file generated for musy on 2023-06-05T19:37:56-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "musy"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  NODE_ENV="production"

[experimental]
  cmd = ["start.sh"]
  entrypoint = ["sh"]
  auto_rollback = true

[mounts]
  source = "musy_data_v4_machines"
  destination = "/data"
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
